import java.util.Properties
import java.security.MessageDigest
import java.security.SecureRandom

// Paid-module activation secrets. `activation-secrets.gradle.kts` (gitignored, generated by the
// `generateActivationCodes` task) holds `extra["activationSalt"]` and `extra["activationHashes"]`.
// We read the file directly and regex-extract the two quoted values. This intentionally avoids
// `apply(from = ...)` + project extras: in the Kotlin DSL that path does not reliably surface the
// applied script's values to this build script (and is fragile under configuration cache), which
// left BuildConfig.ACTIVATION_* empty even when the secrets file existed. When the file is absent
// (e.g. a clean clone from github) both stay empty and activation is simply disabled — the build
// still succeeds.
val activationSecretsFile = rootProject.file("activation-secrets.gradle.kts")
val activationSalt: String
val activationHashes: String
if (activationSecretsFile.exists()) {
    val secretsText = activationSecretsFile.readText()
    fun extractSecret(key: String): String =
        Regex("""extra\["${key}"\]\s*=\s*"([^"]*)"""").find(secretsText)?.groupValues?.get(1).orEmpty()
    activationSalt = extractSecret("activationSalt")
    activationHashes = extractSecret("activationHashes")
} else {
    activationSalt = ""
    activationHashes = ""
}

plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
    id("org.jetbrains.kotlin.plugin.compose")
}

android {
    namespace = "com.krystals.app"
    compileSdk = 36

    defaultConfig {
        applicationId = "com.krystals.app"
        minSdk = 26
        targetSdk = 36
        versionCode = 1
        versionName = "1.0.0"
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables { useSupportLibrary = true }
        // Paid-module activation: salt + SHA-256 hashes of the 1000 valid 16-char codes.
        // Injected from activation-secrets.gradle.kts (gitignored). Empty when the file is absent,
        // in which case ActivationManager.isActivated() always returns false.
        buildConfigField("String", "ACTIVATION_SALT", "\"${activationSalt}\"")
        buildConfigField("String", "ACTIVATION_HASHES", "\"${activationHashes}\"")
    }

    sourceSets["main"].assets.srcDir(rootProject.file("res"))
    buildFeatures { compose = true; buildConfig = true }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlinOptions { jvmTarget = "17" }
    packaging {
        resources.excludes += setOf("META-INF/{AL2.0,LGPL2.1}", "META-INF/LICENSE*")
        jniLibs.useLegacyPackaging = true
    }
    // Release signing: populate a keystore.properties (gitignored) next to the repo root with
    //   storeFile=/absolute/path/to/release.keystore
    //   storePassword=...
    //   keyAlias=...
    //   keyPassword=...
    // then `./gradlew :app:assembleRelease` will sign the APK. Absent the file, release builds
    // remain unsigned (you can still sign with apksigner afterwards).
    val keystoreProps = rootProject.file("keystore.properties")
    if (keystoreProps.exists()) {
        val props = Properties()
        keystoreProps.inputStream().use { props.load(it) }
        signingConfigs.create("release") {
            storeFile = file(props.getProperty("storeFile"))
            storePassword = props.getProperty("storePassword")
            keyAlias = props.getProperty("keyAlias")
            keyPassword = props.getProperty("keyPassword")
        }
    }
    buildTypes {
        debug { isDebuggable = true }
        release {
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
            if (keystoreProps.exists()) signingConfig = signingConfigs.getByName("release")
        }
    }
}

dependencies {
    implementation(project(":crystal-core"))
    implementation(project(":renderer"))
    val composeBom = platform("androidx.compose:compose-bom:2026.06.00")
    implementation(composeBom)
    androidTestImplementation(composeBom)
    implementation("androidx.activity:activity-compose:1.12.4")
    implementation("androidx.core:core-ktx:1.17.0")
    implementation("androidx.lifecycle:lifecycle-viewmodel-compose:2.10.0")
    implementation("androidx.lifecycle:lifecycle-runtime-compose:2.10.0")
    implementation("androidx.compose.ui:ui")
    implementation("androidx.compose.ui:ui-tooling-preview")
    implementation("androidx.compose.foundation:foundation")
    implementation("androidx.compose.material3:material3")
    implementation("androidx.compose.material:material-icons-extended")
    implementation("com.squareup.okhttp3:okhttp:4.12.0")
    debugImplementation("androidx.compose.ui:ui-tooling")
    testImplementation(kotlin("test"))
    androidTestImplementation("androidx.test.ext:junit:1.3.0")
    androidTestImplementation("androidx.compose.ui:ui-test-junit4")
    debugImplementation("androidx.compose.ui:ui-test-manifest")
}

/**
 * Generates 1000 non-repeating 16-char activation codes and writes two gitignored files into the
 * repo root (both are listed in .gitignore and must never be committed):
 *   - activation-codes.txt           : one plaintext code per line, for the author to distribute.
 *   - activation-secrets.gradle.kts  : `extra["activationSalt"]` + comma-joined SHA-256 hashes,
 *                                       consumed above to populate BuildConfig.ACTIVATION_*.
 *
 * The salt is generated once. If both files already exist the task is a no-op, so re-running it
 * never invalidates codes the author has already handed out. Codes use a 32-symbol alphabet with
 * ambiguous characters (0/O, 1/I/L) removed, and each hash is sha256(salt + code) lowercase hex.
 *
 * Run with:  ./gradlew :app:generateActivationCodes
 */
tasks.register("generateActivationCodes") {
    group = "krystals"
    description = "Generate 1000 activation codes and their SHA-256 hashes for the paid module."

    val codesFile = rootProject.file("activation-codes.txt")
    val secretsFile = rootProject.file("activation-secrets.gradle.kts")

    // Re-run only when neither output exists; once codes are distributed the salt must stay fixed.
    outputs.upToDateWhen { codesFile.exists() && secretsFile.exists() }

    doLast {
        if (codesFile.exists() && secretsFile.exists()) {
            logger.lifecycle("Activation codes already present — leaving them untouched so issued codes stay valid.")
            return@doLast
        }
        val alphabet = "23456789ABCDEFGHJKLMNPQRSTUVWXYZ".toCharArray() // 32 symbols, no 0/O/1/I/L
        val random = SecureRandom()
        val digest = MessageDigest.getInstance("SHA-256")

        // 32-char salt: alphanumeric from the same alphabet.
        val salt = (1..32).map { alphabet[random.nextInt(alphabet.size)] }.joinToString("")
        fun hash(code: String): String {
            val bytes = (salt + code).toByteArray(Charsets.UTF_8)
            return digest.digest(bytes).joinToString("") { "%02x".format(it) }
        }

        val codes = LinkedHashSet<String>()
        while (codes.size < 1000) {
            val code = (1..16).map { alphabet[random.nextInt(alphabet.size)] }.joinToString("")
            codes.add(code)
        }

        codesFile.writeText(codes.joinToString("\n", postfix = "\n"))
        val hashes = codes.joinToString(",") { hash(it) }
        // Write the secrets as a Kotlin script that sets project extras. Each string is emitted
        // as a Kotlin-quoted literal with backslash escaping so any character survives.
        fun kotlinLiteral(s: String): String = "\"" + s.replace("\\", "\\\\").replace("\"", "\\\"") + "\""
        secretsFile.writeText(
            """
            // Auto-generated by :app:generateActivationCodes — DO NOT COMMIT (gitignored).
            // Paid-module activation secrets for Krystals.
            extra["activationSalt"] = ${kotlinLiteral(salt)}
            extra["activationHashes"] = ${kotlinLiteral(hashes)}
            """.trimIndent() + "\n"
        )

        logger.lifecycle("Generated ${codes.size} activation codes -> ${codesFile.name}")
        logger.lifecycle("Wrote activation secrets   -> ${secretsFile.name}")
        logger.lifecycle("Both files are gitignored; do not commit them. Distribute ${codesFile.name} to sponsors.")
    }
}
